name: Send APK to AppCenter
on:
  push:

jobs:

  apk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11  // you need to define JDK version here
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Manage Version
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: app/build.gradle
          versionCode: ${{github.run_number}} 
          versionName: 1.0.0

      - name: Grant Permission to Execute
        run: chmod +x gradlew

      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace

      - name: Upload APK to Github Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Distribute to AppCenter
        uses: wzieba/AppCenter-Github-Action@v1.3.2
        with:
          appName: ${{secrets.APP_CENTER_APP_NAME}}
          token: ${{ secrets.APP_CENTER_TOKEN }}
          group: Collaborators
          file: app/build/outputs/apk/debug/app-debug.apk
          notifyTesters: true
          debug: false
